
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARRAY BLACK BLUE BST CANVAS DEF DIMENSIONS DLL POSITION QUEUE STACK STRUCT STRUCTURES colon comma digit false greater_than integer left_bracket left_parenthesis less_than right_bracket right_parenthesis true\n        Func : DEF CANVAS Canvas DEF STRUCTURES Structure\n    \n        Bool : true\n             | false\n    \n        Canvas : left_parenthesis Dimensions Position right_parenthesis\n    \n        Position : POSITION colon less_than integer comma integer greater_than\n    \n        Dimensions : DIMENSIONS colon less_than integer comma integer greater_than\n    \n        Color : BLACK\n              | BLUE\n    \n        Structure : left_parenthesis Struct right_parenthesis              \n    \n        Struct : STRUCT colon DataStructure\n    \n        DataStructure : ARRAY\n                      | QUEUE\n                      | STACK\n                      | DLL\n                      | BST\n    \n    Int : digit \n        | digit integer\n    '
    
_lr_action_items = {'DEF':([0,4,15,],[2,6,-4,]),'$end':([1,13,22,],[0,-1,-9,]),'CANVAS':([2,],[3,]),'left_parenthesis':([3,9,],[5,14,]),'DIMENSIONS':([5,],[8,]),'STRUCTURES':([6,],[9,]),'POSITION':([7,35,],[11,-6,]),'colon':([8,11,19,],[12,16,23,]),'right_parenthesis':([10,18,26,27,28,29,30,31,36,],[15,22,-10,-11,-12,-13,-14,-15,-5,]),'less_than':([12,16,],[17,20,]),'STRUCT':([14,],[19,]),'integer':([17,20,25,32,],[21,24,33,34,]),'comma':([21,24,],[25,32,]),'ARRAY':([23,],[27,]),'QUEUE':([23,],[28,]),'STACK':([23,],[29,]),'DLL':([23,],[30,]),'BST':([23,],[31,]),'greater_than':([33,34,],[35,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Func':([0,],[1,]),'Canvas':([3,],[4,]),'Dimensions':([5,],[7,]),'Position':([7,],[10,]),'Structure':([9,],[13,]),'Struct':([14,],[18,]),'DataStructure':([23,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Func","S'",1,None,None,None),
  ('Func -> DEF CANVAS Canvas DEF STRUCTURES Structure','Func',6,'p_Func','parser.py',24),
  ('Bool -> true','Bool',1,'p_Bool','parser.py',31),
  ('Bool -> false','Bool',1,'p_Bool','parser.py',32),
  ('Canvas -> left_parenthesis Dimensions Position right_parenthesis','Canvas',4,'p_Canvas','parser.py',39),
  ('Position -> POSITION colon less_than integer comma integer greater_than','Position',7,'p_Position','parser.py',46),
  ('Dimensions -> DIMENSIONS colon less_than integer comma integer greater_than','Dimensions',7,'p_Dimensions','parser.py',52),
  ('Color -> BLACK','Color',1,'p_Color','parser.py',59),
  ('Color -> BLUE','Color',1,'p_Color','parser.py',60),
  ('Structure -> left_parenthesis Struct right_parenthesis','Structure',3,'p_Structure','parser.py',67),
  ('Struct -> STRUCT colon DataStructure','Struct',3,'p_Struct','parser.py',73),
  ('DataStructure -> ARRAY','DataStructure',1,'p_DataStructure','parser.py',79),
  ('DataStructure -> QUEUE','DataStructure',1,'p_DataStructure','parser.py',80),
  ('DataStructure -> STACK','DataStructure',1,'p_DataStructure','parser.py',81),
  ('DataStructure -> DLL','DataStructure',1,'p_DataStructure','parser.py',82),
  ('DataStructure -> BST','DataStructure',1,'p_DataStructure','parser.py',83),
  ('Int -> digit','Int',1,'p_int','parser.py',90),
  ('Int -> digit integer','Int',2,'p_int','parser.py',91),
]
